// Define the topics and their corresponding keywords
const topics = {
  Basics: [
    "nervos network",
    "nervos ckb",
    "ckb wallet",
    "ckb nervos",
    "ckb nervos network",
    "nervos wallet",
    "nervos network ckb",
    "nervos network wallet",
    "the nervos network",
    "wallet ckb",
    "wallet for ckb",
    "ckb network",
    "ckb nervos wallet",
    "ckb exchanges",
    "wallet integration",
    "nervos ckb wallet",
    "nervos exchange",
    "mining",
    "explorer",
    "faucet",
    "neuron",
    "wallet",
    "neuron wallet",
  ],
  Reference: [
    "cell",
    "lock script",
    "live cell",
    "ckb",
    "hash",
    "transaction",
    "hash_type",
    "tx_hash",
    "index",
    "state change",
    "rpc",
    "json",
    "json-rpc",
    "jsonrpc",
    "epoch",
    "ckbyte",
    "halving",
    "base issuance",
    "issuance",
  ],
  Labs: [
    "script",
    "input",
    "sudt",
    "arg",
    "context",
    "capsule",
    "exec",
    "syscall",
    "testing",
    "sub-script",
    "dynamic loading",
  ],
  Integrate: [
    "mainnet",
    "integration",
    "server requirements",
    "CKB Address Format",
    "indexer",
    "sdk",
  ],
  Essays: [
    "tips",
    "guide",
    "PW-lock",
    "integrity check",
    "script dependencies",
  ],
};

exports.topics = topics;
